exports.handlingOptions = [
  {
    key: 'vecCentreOfMassOffset',
    min: -1,
    max: 1,
    step: 0.01,
    hint: 'This value shifts the center of gravity in meters from side to side (when in vehicle looking forward).',
    type: 'vector3',
  },
  //TODO VALUES
  {
    key: 'fDownforceModifier',
    min: 0.01,
    max: 100,
    step: 0.01,
    hint: 'Sets the amount of downforce applied to the vehicle. Increase this value to increase the grip at high speed.',
    type: 'number',
  },
  {
    key: 'vecInertiaMultiplier',
    min: 0.01,
    max: 4,
    step: 0.01,
    hint: 'This value is resistance to rotation around each axis. Therefore, the x axis affects how quickly the car shifts forward and back under braking and acceleration and how it rotates end over end in the air, the y axis affects how quickly the car shifts from side to side when cornering (or in the air) and the z axis affects how the car rotates around the middle, which manifests in normal driving as how quickly the vehicle appears to react to steering inputs. Recommend keeping the z value above 2.0 unless you want arcade style immediate reaction to steering inputs',
    type: 'vector3',
  },
  {
    key: 'fInitialDragCoeff',
    min: 10,
    max: 240,
    step: 1,
    hint: 'Sets the drag coefficient on the rage physics archetype of the vehicle (proportional to velocity squared). Increase to simulate aerodynamic drag. This affects the maximum speed of the vehicle. Max 120 Greater value will lower the maximum speed.',
    type: 'number',
  },
  {
    key: 'fMass',
    min: 50,
    max: 10000,
    step: 50,
    hint: 'This is the weight of the vehicle in kilograms. Only used when the vehicle collides with another vehicle or non-static object.',
    type: 'number',
  },
  {
    key: 'fPercentSubmerged',
    min: 0,
    max: 100,
    step: 1,
    hint: 'A percentage of vehicle height in the water before vehicle floats. So as the vehicle falls into the water, at 85% vehicle height (seemingly the default for road vehicles) it will stop sinking to float for a moment before it sinks (boats excluded).',
    type: 'number',
  },
  // ! END DIVIDER PHYSICAL
  { type: 'divider', hint: 'Transmission', key: '_', min: 0, max: 0, step: 0 },
  {
    key: 'fClutchChangeRateScaleDownShift',
    min: 0.01,
    max: 15,
    step: 0.01,
    hint: 'Clutch speed multiplier on up shifts, bigger number = faster shifts. Recommended to not go over 13. A value of 1 = 0.9 seconds to shift gears',
    type: 'number',
  },
  {
    key: 'fClutchChangeRateScaleUpShift',
    min: 0.01,
    max: 15,
    step: 0.01,
    hint: 'Clutch speed multiplier on down shifts, bigger number = faster shifts. Recommended to not go over 13. A value of 1 = 0.9 seconds to shift gears.',
    type: 'number',
  },
  {
    key: 'fDriveBiasFront',
    min: 0,
    max: 1,
    step: 0.01,
    hint: 'This value is used to determine whether a vehicle is front, rear, or four wheel drive. 0.0 is rear wheel drive, 1.0 is front wheel drive, and any value between 0.01 and 0.99 is four wheel drive (0.5 give both front and rear axles equal force, being perfect 4WD.)',
    type: 'number',
  },
  {
    key: 'fDriveInertia',
    min: 0.01,
    max: 2,
    step: 0.01,
    hint: 'Describes how fast an engine will rev. For example an engine with a long stroke crank and heavy flywheel will take longer to redline than an engine with a short stroke and light flywheel. Default value is 1.0, or no modification of drive intertia. Bigger value = quicker redline',
    type: 'number',
  },
  {
    key: 'fHandBrakeForce',
    min: 0.01,
    max: 100,
    step: 0.01,
    hint: 'Braking power for handbrake. Bigger number = harder braking',
    type: 'number',
  },
  {
    key: 'fInitialDriveForce',
    min: 0.001,
    max: 10,
    step: 0.001,
    hint: 'This value specifies the drive force of the car, at the wheels. 1.0 uses drive force calculation unmodified. Values less than 1.0 will in effect give the vehicle less drive force and values greater than 1.0 will produce more drive force. Most cars have between 0.10 and 0.40. This value is calculated with the vehicle weight, so heavy and light vehicles have an accurate acceleration.',
    type: 'number',
  },
  {
    key: 'nInitialDriveGears',
    min: 0,
    max: 10,
    step: 1,
    hint: "How many forward speeds a transmission contains. It is not recommended to have a value higher than 8 here as issues with downshifting can occur if the car's top gear is 9 or higher.",
    type: 'number',
  },
  {
    key: 'fInitialDriveMaxFlatVel',
    min: 0.01,
    max: 200,
    step: 0.01,
    hint: "Determines the speed at redline in top gear; Controls the final drive of the vehicle's gearbox. Setting this value does not guarantee the vehicle will reach this speed. Multiply the number in the file by 0.82 to get the speed in mph or multiply by 1.32 to get kph. To find the right value for a given kph figure, kph * 0.75. To convert mph, multiply by 1.22. 'TopSpeedKph = (InitialDriveMaxFlatVel * 1.2) / 0.9' The top speeds for different gears can be calculated by replacing the 0.9 in the formula with the ratio of the specific gear. GTA V uses a ratio of 0.9 for the top gear by default.",
    type: 'number',
  },
  {
    key: 'fSteeringLock',
    min: 0.001,
    max: 2,
    step: 0.001,
    hint: "This value is a multiplier of the game's calculation of the angle a steer wheel will turn while at full turn. Steering lock is directly related to over or understeer / turning radius. Values around 0.1 - 0.2 will simulate a long wheelbase. Whereas a value of around 0.75 and above will turn extremely fast. To high of a value here will cause the vehicle to spin out too easily.",
    type: 'number',
    toRage: val => val*0.017453292,
    fromRage: val => val/0.017453292,
  },
  // ! END DIVIDER TRANSMISSION
  {
    key: 'fBrakeBiasFront',
    min: 0.001,
    max: 2,
    step: 0.001,
    hint: 'This controls the distribution of braking force between the front and rear axles. 0.0 means the rear axle only receives brake force, 1.0 means the front axle only receives brake force. 0.5 gives both axles equal brake force. A value between 0.01 and 0.49 means the rear axle will receive more brake force than the front and a value between .051 and 0.99 means the front axles will receive more brake force than the rear. In real life, normal vehicles usually have more front braking force than the rear (eg., 0.65).',
    type: 'number',
    toRage: val => val*2,
    fromRage: val => val/2,
  },
  {
    key: 'fBrakeForce',
    min: 0.001,
    max: 10,
    step: 0.001,
    hint: "Multiplies the game's calculation of deceleration. Bigger number = harder braking. 1.0 uses brake force calculation unmodified.",
    type: 'number',
  },
  { type: 'divider', hint: 'Traction', key: '_', min: 0, max: 0, step: 0 },
  {
    key: 'fCamberStiffnesss',
    min: -1,
    max: 3,
    step: 0.01,
    hint: 'How much the vehicle is pushed towards its roll direction. Road camber also affects roll and applied forces. Values smaller than 0.0 or greater than 1.0 create unrealistic forces.',
    type: 'number',
  },
  {
    key: 'fLowSpeedTractionLossMult',
    min: 0,
    max: 4,
    step: 0.01,
    hint: 'How much traction is reduced at low speed, 0.0 means normal traction. It affects mainly car burnout (spinning wheels when car doesnt move) when pressing gas. Decreasing value will cause less burnout, less sliding at start. However, the higher value, the more burnout car gets. Optimal is 1.0. A completely artificial force.',
    type: 'number',
  },
  //TODO ALL TRACTION VALUES
  {
    key: 'fTractionBiasFront',
    min: 0.001,
    max: 2,
    step: 0.001,
    hint: 'Determines the distribution of traction from front to rear. 0.01 = only rear axle has traction. 0.99 = only front axle has traction. 0.5 = both axles have equal traction. Entering a value of 0.0 or 1.0 causes the vehicle to have no traction (the tires actually fail to spawn), while entering a value outside of specified range causes the car to move irrationally whenever the wheels are touching the ground.',
    type: 'number',
    toRage: val => val*2,
    fromRage: val => val/2,
  },
  {
    key: 'fTractionCurveLateral',
    min: 0.001,
    max: 10,
    step: 0.001,
    hint: "Shape of lateral traction curve (peak traction position in degrees). Lower values make the vehicle's grip more responsive but less forgiving to loss of traction. Higher values make the vehicle's grip less responsive but more forgiving to loss of traction. Also known as 'slip angle'.",
    type: 'number',
    toRage: val => val*0.017453292,
    fromRage: val => val/0.017453292,
  },
  {
    key: 'fTractionCurveMax',
    min: 0.001,
    max: 5,
    step: 0.001,
    hint: 'Cornering grip of the vehicle as a multiplier of the tire surface friction. Effectively the peak grip status before any loss of grip.',
    type: 'number',
  },
  {
    key: 'fTractionCurveMin',
    min: 0.001,
    max: 5,
    step: 0.001,
    hint: 'Accelerating/braking grip of the vehicle as a multiplier of the tire surface friction. Effectively the minimum grip status after losing traction, e.g. in a skidding situation.',
    type: 'number',
  },
  {
    key: 'fTractionLossMult',
    min: 0.001,
    max: 4,
    step: 0.001,
    hint: 'How much is traction affected by material grip differences from 1.0. Basically it affects how much grip is changed when driving on asphalt and mud (the higher, the more grip you loose, making car less responsive and prone to sliding).',
    type: 'number',
  },
  {
    key: 'fTractionSpringDeltaMax',
    min: 0.001,
    max: 10,
    step: 0.001,
    hint: 'Max distance of the lateral sidewall travel. Unit: meter. A force will pull the vehicle in the opposite direction of the lateral travel, most noticeable when stopping after a slide. The dynamic effect is a small force pulling the vehicle inwards of a corner, more noticeable as the sliding angle increases.',
    type: 'number',
  },
  // ! END DIVIDER WHEEL TRACTION
  { type: 'divider', hint: 'Suspension', key: '_', min: 0, max: 0, step: 0 },
  {
    key: 'fAntiRollBarBiasFront',
    min: 0.001,
    max: 2,
    step: 0.001,
    hint: 'The bias between front and rear for the antiroll bar(0 front, 1 rear)',
    type: 'number',
    toRage: val => val*2,
    fromRage: val => val/2,
  },
  {
    key: 'fAntiRollBarForce',
    min: 0.001,
    max: 5,
    step: 0.001,
    hint: 'The spring constant that is transmitted to the opposite wheel when under compression larger numbers are a larger force. Larger Numbers = less body roll',
    type: 'number',
  },
  {
    key: 'fRollCentreHeightFront',
    min: 0.001,
    max: 2,
    step: 0.001,
    hint: 'The roll center height for the front axle, from the bottom of the model (road), in meters. High values place the roll center closer to the center of mass, reducing body roll. Values placing the roll center higher than the center of mass will induce negative body roll - the "Tyrus Effect". Low values increase the roll center distance from the center of mass, increasing body roll. Values placing the roll center too far from the center of mass may increase rollover chances. Since center of mass differs per vehicle, using a visualization tool may help determining a desired amount of body roll.',
    type: 'number',
  },
  {
    key: 'fRollCentreHeightRear',
    min: 0.001,
    max: 2,
    step: 0.001,
    hint: 'The roll center height for the rear axle, from the bottom of the model (road), in meters. High values place the roll center closer to the center of mass, reducing body roll. Values placing the roll center higher than the center of mass will induce negative body roll - the "Tyrus Effect". Low values increase the roll center distance from the center of mass, increasing body roll. Values placing the roll center too far from the center of mass may increase rollover chances. Since center of mass differs per vehicle, using a visualization tool may help determining a desired amount of body roll.',
    type: 'number',
  },
  {
    key: 'fSuspensionBiasFront',
    min: 0.001,
    max: 1,
    step: 0.001,
    hint: 'Force damping scale front/back. If more wheels at back (e.g. trucks) need front suspension to be stronger. This value determines which suspension is stronger, front or rear. If value is above 0.50 then front is stiffer, when below, rear.',
    type: 'number',
    toRage: val => val*2,
    fromRage: val => val/2,
  },
  {
    key: 'fSuspensionCompDamp',
    min: 0,
    max: 30,
    step: 0.01,
    hint: 'Damping during strut compression. Bigger = stiffer.',
    type: 'number',
    toRage: val => val/10,
    fromRage: val => val*10,
  },
  {
    key: 'fSuspensionForce',
    min: 0,
    max: 30,
    step: 0.01,
    hint: '1 / (Force * NumWheels) = Lower limit for zero force at full extension. Affects how strong suspension is. Can help if car is easily flipped over when turning.',
    type: 'number',
  },
  {
    key: 'fSuspensionLowerLimit',
    min: -2,
    max: 0.5,
    step: 1,
    hint: 'Visual limit... how far can wheels move up / down from original position',
    type: 'number',
  },
  {
    key: 'fSuspensionRaise',
    min: -0.2,
    max: 0.5,
    step: 0.001,
    hint: 'The amount that the suspension raises the body off the wheels. Recommend adjusting at second decimal unless vehicle has room to move. ie -0.02 is plenty of drop on an already low car. Too much will show the wheels clipping through or if positive, no suspension joining the body to wheels',
    type: 'number',
  },
  {
    key: 'fSuspensionReboundDamp',
    min: 0,
    max: 30,
    step: 0.01,
    hint: 'Damping during strut rebound. Bigger = stiffer',
    type: 'number',
    toRage: val => val/10,
    fromRage: val => val*10,
  },
  {
    key: 'fSuspensionUpperLimit',
    min: -0.5,
    max: 2,
    step: 0.01,
    hint: 'Visual limit... how far can wheels move up / down from original position',
    type: 'number',
  },
  // ! END DIVIDER SUSPENSION
  { type: 'divider', hint: 'Damage', key: '_', min: 0, max: 0, step: 0 },
  {
    key: 'fCollisionDamageMult',
    min: 0,
    max: 10,
    step: 0.01,
    hint: 'Multiplies the games calculation of damage to the vehicle through collision, causing gas tank and wheels to catch fire. 0.0 = no damage through collision. 10.0 = Ten times damage through collision. Higher values make body parts fall off more easily. Also enables engine damage.',
    type: 'number',
  },
  {
    key: 'fDeformationDamageMult',
    min: 0,
    max: 10,
    step: 0.01,
    hint: 'Multiplies the games calculation of deformation-causing damage. 0.0 = no deformation through damage is possible. 10.0 = Ten times deformation-causing damage.',
    type: 'number',
  },
  {
    key: 'fEngineDamageMult',
    min: 0,
    max: 10,
    step: 0.01,
    hint: 'Multiplies the games calculation of damage to the engine, causing explosion or engine failure. 0.0 = no damage to the engine. 10.0 = Ten times damage to the engine. This value seems to respond mostly to impacts directly on the hood, and not as much to front end impacts (particularly with taller vehicles).',
    type: 'number',
  },
  {
    key: 'fWeaponDamageMult',
    min: 0,
    max: 10,
    step: 0.01,
    hint: 'Multiplies the games calculation of damage to the vehicle through weapon damage. 0.0 = no damage through weapons. 10.0 = Ten times damage through weapons.',
    type: 'number',
  },
  { key: 'fOilVolume', min: 0, max: 20, step: 0.1, hint: 'Black smoke time before engine dies?', type: 'number' },
  {
    key: 'fPetrolTankVolume',
    min: 0,
    max: 1000,
    step: 10,
    hint: 'Amount of petrol that will leak after shooting the vehicles petrol tank. Also used by some fuel-usage scripts.',
    type: 'number',
  },
  // ! END DIVIDER DAMAGE
  { type: 'divider', hint: 'Misc', key: '_', min: 0, max: 0, step: 0 },
  {
    key: 'strHandlingFlags',
    min: 0,
    max: 32,
    step: 1,
    hint: 'Affects handling-related functions. See Wiki for Explanations.',
    type: 'flags',
  },
  {
    key: 'strModelFlags',
    min: 0,
    max: 32,
    step: 1,
    hint: 'Affects model-related functions. See Wiki for explanations.',
    type: 'flags',
  },
  {
    key: 'strDamageFlags',
    min: 0,
    max: 6,
    step: 1,
    hint: 'Indicates the doors that are nonbreakable. See wiki for Explanations.',
    type: 'flags',
  },
  { key: 'nMonetaryValue', min: 0, max: 999999, step: 1, hint: 'Vehicle worth.', type: 'number' },
  // {
  //   key: 'fSeatOffsetDistX',
  //   min: -2,
  //   max: 2,
  //   step: 0.01,
  //   hint: 'The distance from the door to the car seat. Driver > passenger',
  //   type: 'number',
  // },
  // {
  //   key: 'fSeatOffsetDistY',
  //   min: -2,
  //   max: 2,
  //   step: 0.01,
  //   hint: 'The distance from the door to the car seat. Trunk > hood',
  //   type: 'number',
  // },
  // {
  //   key: 'fSeatOffsetDistZ',
  //   min: -10,
  //   max: 10,
  //   step: 0.01,
  //   hint: 'The distance from the door to the car seat. Undercarriage > roof',
  //   type: 'number',
  // },
  // ! END DIVIDER MISC
];